// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFaz-CwdwBgIbo6TRjR_LT0rgyGi2TOHI',
    appId: '1:132564343334:android:05735b27be74c0a444a4e7',
    messagingSenderId: '132564343334',
    projectId: 'traincoach-2ef9d',
    storageBucket: 'traincoach-2ef9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdXiaoQMteUa9rmH3D56CLhoXpPhJgZuA',
    appId: '1:132564343334:ios:c7a1e04b3dd95cda44a4e7',
    messagingSenderId: '132564343334',
    projectId: 'traincoach-2ef9d',
    storageBucket: 'traincoach-2ef9d.firebasestorage.app',
    iosBundleId: 'com.example.appgym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEbvgpdnmEDCMu4MlAZNN0kASWyFeg-ng',
    appId: '1:132564343334:web:f22c6aac4949f74444a4e7',
    messagingSenderId: '132564343334',
    projectId: 'traincoach-2ef9d',
    authDomain: 'traincoach-2ef9d.firebaseapp.com',
    storageBucket: 'traincoach-2ef9d.firebasestorage.app',
    measurementId: 'G-X8EGRNSCVP',
  );

}