name: build_and_preview

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./web-app
        run: npm install

      - name: Build project
        working-directory: ./web-app
        run: npm run build

      - name: Deploy to Firebase (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRAINCOACH_WEB }}"
          projectId: traincoach-2ef9d
          channelId: pr-${{ github.event.pull_request.number }}
